### ISSUE TITLE
Projects that have billing disabled break the access group cache

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/analysis-runner#335]
Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1645999698296499?thread_ts=1645970605.333669&cid=C018KFBCR1C

Logs:
```
2022-02-28 09:05:24.326 AEDT Traceback (most recent call last): File "/root/micromamba/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable return callable_(*args, **kwargs) File "/root/micromamba/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/root/micromamba/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
2022-02-28 09:05:24.326 AEDT status = StatusCode.PERMISSION_DENIED
2022-02-28 09:05:24.326 AEDT details = "This API method requires billing to be enabled. Please enable billing on project #583112281444 by visiting https://console.developers.google.com/billing/enable?project=583112281444 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."
Default
2022-02-28 09:05:24.326 AEDT debug_error_string = "{"created":"@1645999524.324945402","description":"Error received from peer ipv4:172.217.24.42:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"This API method requires billing to be enabled. Please enable billing on project #583112281444 by visiting https://console.developers.google.com/billing/enable?project=583112281444 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.","grpc_status":7}"
Default
```

**Comment by illusional** [comment]
This is failing on `write_secret` because no billing account is attached: https://github.com/populationgenomics/analysis-runner/blob/e2dd7b4a55fcb69e9954d84f5c166c9bdfe76d55/access_group_cache/main.py#L210

I think the appropriate fix is to catch and store these exceptions, and throw them all at the end to at least keep the access-group-cache working for other projects.

More interesting, is that the value of the secret didn't actually change but it attempted to write a new secret version (between 73 [07/02/2022 10:16] AND 74 [28/02/2022, 09:10]). I wonder if accessing secret version also failed or something?

**Comment by illusional** [comment]
Closed by removing the group cache polling mechanism in https://github.com/populationgenomics/cpg-infrastructure/pull/33
